### ISSUE TITLE
I can't get coins out of the nominator pool for more than 30 hours.

### ISSUE THREAD

**Issue by SomeAssist** [ton-blockchain/nominator-pool#6]
Hello,

I can't get coins out of the nominator pool for more than 30 hours.
The validator was active 4 days ago.
Can you help me with this?

nominator pool
https://tonscan.org/nominator/Ef_ptWxvN6RAoA9jEnzDc6UdfmeuMTjS-gbZ9zqp-SdtpsiX

**Comment by EmelyanenkoK** [comment]
Hi, pool-contract provides way for nominators to force pool to get money from the elector and then return them to nominators, even when validator is dormant. Unfortunately there is no simple interface for that yet, so for now we sent required message to pool for you, you should be able withdraw money now.
