### ISSUE TITLE
Can a Validator run multiple nominator-pools that are all connected to the same mytonctrl instance?

### ISSUE THREAD

**Issue by sbond14** [ton-blockchain/nominator-pool#9]
From what I understand, there is nothing stopping a validator entity from running just a single instance of mytonctrl, and connecting it to multiple nominator-pool instances. Is this stopped by the network somehow? Or is it actually possible for a validator to "cheat" the network like this?

**Comment by sbond14** [comment]
By mutliple, I mean more than 2. But I feel like mytonctrl would only have one pool get elected, so the others would just be unused. Is that correct?

**Comment by EmelyanenkoK** [comment]
There is no option in node to validate on behalf of multiple validators (winners of elections), so there is no reason to attach more than two nominator-pools (for even and odd rounds) to one mtc
